/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.Controller;
import Model.Booking;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class View_HistoryBooking extends javax.swing.JFrame {

    private final DefaultTableModel model = new DefaultTableModel();
    private Controller koneksiData = new Controller();
    /**
     * Creates new form View_HistoryBooking
     */
    public View_HistoryBooking() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        // Memtikan resize
        setResizable(false);

        // tabel
        model.addColumn("ID");
        model.addColumn("Nama Konsumen");
        model.addColumn("No Telepon");
        model.addColumn("Tanggal");
        model.addColumn("Jam Booking");
        model.addColumn("Lapangan");
        model.addColumn("Status");
        

        TabelHistori.setModel(model);

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelHistori = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ButBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabSubJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(541, 451));
        setMinimumSize(new java.awt.Dimension(541, 451));
        setPreferredSize(new java.awt.Dimension(541, 451));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 513, -1));

        TabelHistori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelHistori);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 133, 480, 210));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Histori Booking");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 84, -1, -1));

        ButBack.setBackground(new java.awt.Color(255, 0, 0));
        ButBack.setText("Back");
        ButBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBackActionPerformed(evt);
            }
        });
        getContentPane().add(ButBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENYEWAAN LAPANGAN");
        jPanel1.add(jLabel1);

        LabSubJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabSubJudul.setText("Aplikasi Booking Penyewaan Lapangan");
        jPanel1.add(LabSubJudul);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBackActionPerformed
        new View_ListBookingPage().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ButBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_HistoryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_HistoryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_HistoryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_HistoryBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_HistoryBooking().setVisible(true);
            }
        });
    }
    
    private void populateTable() {
    model.setRowCount(0);
    try {
        ArrayList<Booking> lihat = koneksiData.tampilHistoriBooking();
        for (Booking b : lihat) {
            Object[] isiData = {b.getId_booking(), b.getNamaKonsumen(), b.getNotelepon(), b.getTanggal(), b.getStart_jam(), b.getEnd_jam(), b.getTotalHarga(), b.getStatus()};
            model.addRow(isiData);
        }
    } catch (SQLException ex) {
        System.out.println("Eksepsi: " + ex.getMessage());
        JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButBack;
    private javax.swing.JLabel LabSubJudul;
    private javax.swing.JTable TabelHistori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
