/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.View_ListBookingPage;
import view.View_loginPage;

/**
 *
 * @author lenovo
 */
public class View_registerPage extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    View_ListBookingPage masuk = new View_ListBookingPage();

    public View_registerPage() {
        initComponents();

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        // Memtikan resize
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        LabPassword = new javax.swing.JLabel();
        LabUsername = new javax.swing.JLabel();
        LabJudul = new javax.swing.JLabel();
        SubJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(541, 451));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfUsernameMouseClicked(evt);
            }
        });
        TfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(TfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 149, 210, -1));

        btnRegister.setBackground(new java.awt.Color(0, 153, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 272, -1, -1));

        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 209, 210, -1));

        LabPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LabPassword.setText("Password");
        getContentPane().add(LabPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        LabUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LabUsername.setText("Username");
        getContentPane().add(LabUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        LabJudul.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        LabJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabJudul.setText("PENYEWAAN LAPANGAN");
        getContentPane().add(LabJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 528, -1));

        SubJudul.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SubJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubJudul.setText("Aplikasi Penyewaan Lapangan");
        getContentPane().add(SubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 528, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfUsernameMouseClicked
        TfUsername.setText("");
    }//GEN-LAST:event_TfUsernameMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            
            String username = TfUsername.getText();
            String password = String.valueOf(Password.getPassword());
            
           if(username.equals("")){
    JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!"); 
    return;
}

if(password.equals("")){
    JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!"); 
    return;
}

            boolean usernameExists = false;
            java.sql.Connection conn = Connect.dbConnection();
            String getQuery = "SELECT * FROM user WHERE username=?";
            java.sql.PreparedStatement getUsernameStatement = conn.prepareStatement(getQuery);
            getUsernameStatement.setString(1, username.toLowerCase());
            java.sql.ResultSet rset = getUsernameStatement.executeQuery();

            if (rset.next()) {
                usernameExists = true;
            }

            if (usernameExists) {
                String message = "Username sudah digunakan!";
                JOptionPane.showMessageDialog(null, message);                
            }

            try {
                String insertQuery = "INSERT INTO user(username, password) VALUES(?, ?)";

                PreparedStatement pstate = conn.prepareStatement(insertQuery);
                pstate.setString(1, username.toLowerCase());
                pstate.setString(2, password);

                int rowAffected = pstate.executeUpdate();

                if (rowAffected > 0) {
                    System.out.println("Insert successfull");
                    JOptionPane.showMessageDialog(null, "Registrasi berhasil");
                    View_loginPage login = new View_loginPage();
                    this.dispose();
                    login.setVisible(true);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Registrasi gagal");
            }
        } catch (SQLException ex) {
            Logger.getLogger(View_registerPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void TfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_registerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabJudul;
    private javax.swing.JLabel LabPassword;
    private javax.swing.JLabel LabUsername;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SubJudul;
    private javax.swing.JTextField TfUsername;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
